name: cd

on:
    push:
        branches: [main]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.23.0"

            - name: Add go bin to PATH
              run: echo "$HOME/go/bin" >> $GITHUB_PATH

            - name: Build App
              run: ./scripts/buildprod.sh

