name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Add go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Test Packages
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Add go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run staticcheck action
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      - name: Check Go Format
        run: test -z $(go fmt ./...)